Repository svthalia/ThaliApp, pull requests merged in 2020-10, with the labels that each got.

#153 Remove react-native-git-upgrade
  package.json
  yarn.lock
Labels: chore

#158 Update renovate config
  renovate.json
Labels: chore

#131 Export events directly to calendar
  __tests__/sagas/event.spec.js
  __tests__/sagas/index.spec.js
  android/app/build.gradle
  app/actions/event.js
  app/sagas/event.js
  app/ui/screens/events/EventScreen.js
  app/ui/screens/events/EventScreenConnector.js
  app/ui/screens/events/style/EventScreen.js
  ios/ThaliApp/Info.plist
  package.json
  yarn.lock
Labels: feature, priority: low

#203 Change update schedule to monthly + group more deps
  renovate.json
Labels: dependency-update

#208 Prevent profile page with error for non-members
  __tests__/ui/components/memberView/MemberView.spec.js
  app/ui/components/memberView/MemberView.js
Labels: bug

#207 Add search bar for calendar events
  __tests__/actions/__snapshots__/calendar.spec.js.snap
  __tests__/actions/calendar.spec.js
  __tests__/reducers/__snapshots__/calendar.spec.js.snap
  __tests__/reducers/calendar.spec.js
  __tests__/sagas/calendar.spec.js
  app/actions/calendar.js
  app/reducers/calendar.js
  app/sagas/calendar.js
  app/ui/screens/events/CalendarScreen.js
  app/ui/screens/events/CalendarScreenConnector.js
  app/ui/screens/events/style/CalendarScreen.js
Labels: events, feature

#210 Fix the registration fields clearing on save
  app/reducers/registration.js
Labels: bug

#206 Fix memberlist resetting the search state after navigation
  __tests__/actions/__snapshots__/members.spec.js.snap
  __tests__/actions/members.spec.js
  __tests__/sagas/navigation.spec.js
  app/actions/members.js
  app/sagas/navigation.js
  app/ui/components/searchHeader/SearchHeader.js
  app/ui/components/sidebar/SidebarConnector.js
Labels: bug
